"""Build REPORT.md for the MPI-INF-3DHP rear-view validation.

Reads:
    data/mpi_inf_3dhp_rear_validation/camera_layout.json
    data/mpi_inf_3dhp_rear_validation/r_cam0.json
    data/mpi_inf_3dhp_rear_validation/r_cam7.json
    data/mpi_inf_3dhp_rear_validation/r_cam3.json (optional, side cam)
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

METRICS_PRETTY = {
    "hip_flexion_r": "Hip flexion R",
    "hip_flexion_l": "Hip flexion L",
    "knee_angle_r": "Knee flexion R",
    "knee_angle_l": "Knee flexion L",
    "ankle_angle_r": "Ankle dorsiflexion R",
    "ankle_angle_l": "Ankle dorsiflexion L",
    "hip_adduction_r": "Hip adduction R",
    "hip_adduction_l": "Hip adduction L",
    "lumbar_extension": "Lumbar extension",
}


def load(path: Path) -> dict | None:
    if not path.exists():
        return None
    with open(path) as f:
        return json.load(f)


def fmt_r(r: float) -> str:
    if r is None or (isinstance(r, float) and r != r):
        return "n/a"
    return f"{r:+.3f}"


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument(
        "--validation-dir",
        default="/Users/cameronvan/Documents/Claude/Projects/Couro/research-agent/multiview-validation/data/mpi_inf_3dhp_rear_validation",
    )
    args = p.parse_args()
    base = Path(args.validation_dir)

    layout = load(base / "camera_layout.json") or {"cameras": []}
    r_cam0 = load(base / "r_cam0.json")
    r_cam7 = load(base / "r_cam7.json")
    r_cam3 = load(base / "r_cam3.json")

    lines: list[str] = []
    lines.append("# MPI-INF-3DHP S1/Seq2 — Rear-view DWPose Validation")
    lines.append("")
    lines.append("Subject: S1 (single, 12,430 frames @ 50 fps), Activity: Sports")
    lines.append("(boxing, tennis, golf, soccer). Processed every 2nd frame "
                 "(~6,215 frames per camera).")
    lines.append("")
    lines.append("Pipeline: DWPose-L (CoreML, 384x288 input, Halpe-26 remap) "
                 "with bounding boxes generated by projecting MPI-INF-3DHP 2D "
                 "GT joint annotations to tight padded boxes (15% pad).")
    lines.append("")
    lines.append("GT angles computed directly from the dataset's 3D mocap "
                 "(`annot3`, camera-0 coords), so they are camera-invariant. "
                 "Predicted angles come from the 2D Halpe-26 keypoints in each "
                 "camera's own image space using Couro's production "
                 "`keypoints_to_motion_data` math.")
    lines.append("")
    lines.append("## Camera layout (S1/Seq2)")
    lines.append("")
    lines.append("| cam | category | rel_az from cam0 | height (mm) | radius (mm) |")
    lines.append("| --- | --- | --- | --- | --- |")
    for c in layout.get("cameras", []):
        lines.append(
            f"| {c['cam_id']} | {c['category']} | {c['rel_az_from_cam0']:+.1f}\xb0 |"
            f" {c['height_mm']:.0f} | {c['radius_mm']:.0f} |"
        )
    lines.append("")
    lines.append(
        "Cam 0 (front-reference) and cam 7 (rear, ~180\xb0 opposite) form the "
        "primary head-to-head. Both at chest height "
        "(~1.2–1.5 m), radius ~3 m."
    )
    lines.append("")
    lines.append("## Pearson r vs 3D mocap GT (frame-level)")
    lines.append("")
    lines.append(
        "Reported as `|r|` so sign-convention differences between predicted 2D "
        "interior angles and GT 3D angles don't muddy comparisons. The sign of "
        "the raw r is consistent within each metric across cameras."
    )
    lines.append("")

    headers = ["Metric"]
    cols: list[dict] = []
    if r_cam0:
        headers.append("Front (cam 0) |r|")
        cols.append({"label": "cam0", "data": r_cam0["results"]})
    if r_cam7:
        headers.append("Rear (cam 7) |r|")
        cols.append({"label": "cam7", "data": r_cam7["results"]})
    if r_cam3:
        headers.append("Side (cam 3) |r|")
        cols.append({"label": "cam3", "data": r_cam3["results"]})
    headers.append("Rear - Front")

    lines.append("| " + " | ".join(headers) + " |")
    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")
    for m, pretty in METRICS_PRETTY.items():
        row = [pretty]
        cam0_abs = cam7_abs = None
        for col in cols:
            r = col["data"][m]["pearson_r"]
            row.append(f"{abs(r):.3f}" if r == r else "n/a")
            if col["label"] == "cam0":
                cam0_abs = abs(r) if r == r else None
            if col["label"] == "cam7":
                cam7_abs = abs(r) if r == r else None
        if cam0_abs is not None and cam7_abs is not None:
            row.append(f"{cam7_abs - cam0_abs:+.3f}")
        else:
            row.append("n/a")
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")

    # Sample size
    if r_cam0:
        n0 = next(iter(r_cam0["results"].values()))["n_frames"]
        lines.append(f"Front cam0 valid-frame count (post conf>0.3 filtering): "
                     f"~{n0:,} frames per metric.")
    if r_cam7:
        n7 = next(iter(r_cam7["results"].values()))["n_frames"]
        lines.append(f"Rear cam7 valid-frame count (post conf>0.3 filtering): "
                     f"~{n7:,} frames per metric.")
    lines.append("")

    lines.append("## Assessment")
    lines.append("")
    lines.append(
        "Rear (cam 7) tracks the same biomechanics as front (cam 0) on the "
        "Couro core metrics:"
    )
    lines.append("")
    lines.append("- Hip flexion (sagittal, primary metric): rear matches or "
                 "beats front (R-side +0.09, L-side +0.02).")
    lines.append("- Knee flexion: rear within 0.07 of front (0.81 vs 0.88 R, "
                 "0.81 vs 0.78 L).")
    lines.append("- Lumbar extension: rear -0.06 vs front (0.81 vs 0.87) — "
                 "still strong.")
    lines.append("- Ankle dorsiflexion: weak from both views (front 0.43 R, "
                 "rear 0.31 R). This metric is dominated by toe keypoint "
                 "noise + 2D foreshortening on either view.")
    lines.append("- Hip adduction (coronal plane): weak from both views "
                 "(<0.30). Expected — 2D coronal measurement is a noisy "
                 "approximation from any single non-frontal camera.")
    lines.append("")
    lines.append("**Verdict**: rear-view models are viable for the three "
                 "metrics that already drive Couro reports (hip flexion, "
                 "knee flexion, lumbar/trunk lean). DWPose does not collapse "
                 "on rear views, contrary to the 'never validated' status of "
                 "the v14 deploy slots. We should ship rear/rear-oblique "
                 "deploys for hip+knee+lumbar; the ankle/adduction metrics "
                 "remain a 3D-angle problem regardless of camera angle.")
    lines.append("")
    lines.append("## Known caveats / failure modes")
    lines.append("")
    lines.append("- **Confidence filtering drops 6–15% of frames** per "
                 "metric (Halpe foot keypoints occasionally drop below 0.3 "
                 "in extreme rear-view poses).")
    lines.append("- **Sign-flipped hip-flexion** in this run: our 2D path "
                 "computes `angle(torso, thigh)` interior whereas GT uses "
                 "`angle(-torso, thigh)`. The signed Pearson is negative for "
                 "all hip-flexion rows; `|r|` is the apples-to-apples number. "
                 "Production motion-data code already applies the "
                 "`180 - interior` flip; this validation script does not.")
    lines.append("- **Single subject (S1) tested.** MPI-INF-3DHP has 8 "
                 "subjects; results may shift on athletic body types vs "
                 "the lab subject.")
    lines.append("- **Stride 2** sampling means effective rate is 25 fps; "
                 "still well-sampled for joint-angle correlations.")
    lines.append("- The studio cameras are **3 m away with subject at "
                 "screen-center**; this is best-case framing. Couro field "
                 "videos with smaller-on-screen subjects may degrade more "
                 "from rear views than from front views.")
    lines.append("")
    lines.append("## Artifacts")
    lines.append("")
    lines.append("- DWPose keypoints: `data/mpi_inf_3dhp_dwpose/"
                 "S1_Seq2_cam{0,3,7}.json`")
    lines.append("- GT angles: `data/mpi_inf_3dhp_gt/S1_Seq2_angles.json`")
    lines.append("- Predicted angles: `data/mpi_inf_3dhp_rear_validation/"
                 "pred_cam{0,3,7}.json`")
    lines.append("- Per-camera correlation tables: `data/"
                 "mpi_inf_3dhp_rear_validation/r_cam{0,3,7}.json`")
    lines.append("- Camera layout: `data/mpi_inf_3dhp_rear_validation/"
                 "camera_layout.json`")
    lines.append("")

    out = base / "REPORT.md"
    out.write_text("\n".join(lines))
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
